#!/bin/bash

BASE="$(cd $(dirname ${BASH_SOURCE[0]}); pwd )"

RESTART="--restart=always"

[ $(id -u) = 0 ] || { echo "Must run as root"; exit 1 ; }
 
docker kill kraiany_site kraiany-nginx
docker rm kraiany_site kraiany-nginx

docker run -d ${RESTART} --name kraiany_site -p 8080:80  kraiany_docker_site
docker run -d ${RESTART} -p 80:80 --name kraiany-nginx --net=host -v ${BASE}/nginx.conf:/etc/nginx/nginx.conf:ro nginx
